app/users/__init__.py
# app/admin/__init__.py

from flask import Blueprint


def import_views():
    from . import views
    from app import models


users = Blueprint('users', __name__)
import_views()

app/users/views.py
# app/home/views.py

from flask import render_template, request, redirect, session, url_for, flash, abort
from app import main_nav, db, login_manager
from . import users
from app.models import User
from sqlalchemy import text
from flask_login import current_user, login_user, login_required, logout_user
import requests
import json
from urllib.parse import urljoin, urlparse


def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, str(target)))
    return test_url.scheme in ('http', 'https') and \
        ref_url.netloc == test_url.netloc


@users.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        data = request.form
        username = data['username']
        password = data['password']
        resp = User.signup_user(username, password)
        print(resp.text)
        if resp.ok:
            return redirect(url_for('home.index'))
        flash('Registration failed. Try again')
    return render_template('users/signup.html', navs=[])


@users.route('/profile', methods=['GET'])
@login_required
def profile():
    navs = main_nav('Home')
    return render_template('users/profile.html', navs=navs)


@users.route('/login', methods=['GET', 'POST'])
def login():
    '''
    if current_user.is_authenticated:
        return redirect(url_for('home.index'))
    '''
    if request.method == 'POST':
        data = request.form
        username = data['username']
        password = data['password']
        resp = User.login_user(username, password)
        if resp.ok:
            res_data = json.loads(resp.text)
            access_token = res_data['access_token']
            refresh_token = res_data['refresh_token']
            session['access_token'] = access_token
            session['refresh_token'] = refresh_token
            user = User.get()
            result = login_user(user)
            if not is_safe_url(next):
                return abort(400)
            flash('You are successfully logged in')
            return redirect(url_for('home.index'))
        flash('Login failed, try again using correct credentials')
    return render_template('users/login.html', navs=[], title="Login")


@users.route('/changepwd', methods=['GET', 'POST'])
@login_required
def changepwd():
    if request.method == 'POST':
        data = request.form
        username = data['username']
        password = data['password']
        resp = User.change_pwd(username, password)
        print('Change pwd response: ', resp.text)
        if resp.ok:
            flash('You are successfully changed password')
            return logout()
    return render_template('users/changepwd.html', navs=[])


@users.route('/logout', methods=['GET'])
@login_required
def logout():
    User.logout_user()
    logout_user()
    flash('You are successfully logged out')
    return redirect(url_for('home.index'))

app/templates/users/changepwd.html
{% extends "base.html" %}

{% block title %}
Change password
{% endblock %}

{% block content %}
<div class="content-wrap">
    <form action="{{ url_for('users.changepwd') }}{% if next %}?next={{ next }}{% endif %}" method="post" id="login-form">
        <h3>Change password form</h3>
        <div class="input-wrap">
            <label for="username">Your username</label>
            <input type="text" name="username" id="username" placeholder="Enter your username" value="{{ current_user.username }}"
                readonly="readonly" />
        </div>
        <div class="input-wrap">
            <label for="password">New password</label>
            <input type="password" name="password" id="password" placeholder="Enter new password" />
        </div>
        <div class="controls input-wrap">
            <button type="submit">Change password</button>
        </div>
    </form>

</div>
{% endblock %}

app/templates/users/login.html
{% extends "base.html" %}

{% block title %}
Login
{% endblock %}

{% block content %}
<div class="content-wrap">
    <form action="{{ url_for('users.login') }}{% if next %}?next={{ next }}{% endif %}" method="post" id="login-form">
        <h3>Login form</h3>
        <div class="input-wrap">
            <label for="username">Username</label>
            <input type="text" name="username" id="username" placeholder="Enter your username" />
        </div>
        <div class="input-wrap">
            <label for="password">Password</label>
            <input type="password" name="password" id="password" placeholder="Enter your password" />
        </div>
        <div class="controls input-wrap">
            <button type="submit">Login</button>
            <input type=hidden value="{{ next or '' }}" name=next />
        </div>

        <div class="signup">
            <span>Not registered?</span>
            <a href="{{ url_for('users.signup') }}">Register</a>
        </div>

    </form>

</div>
{% endblock %}

app/templates/users/profile.html
{% extends "base.html" %}

{% block title %}
Groups
{% endblock %}

{% block breadcrumbs %}
<ul>
    <li><a href="/">Home</a></li>
    <li><span>My profile</span></li>
</ul>
{% endblock %}

{% block content %}
<div class="content-wrap user-profile">
    <section>
        <h3>User info</h3>
        <p>Username: {{ current_user.username}}</p>
        <p>Role: {{ current_user.role or 'None'}}</p>
    </section>
    <section>
        <h3>Member info</h3>
        <ul>
            {% for m in current_user.members %}
            <li>
                {{ m.name}} ({{ m.group.name }})
            </li>
            {% endfor %}
        </ul>
    </section>
</div>
{% endblock %}

app/templates/users/signup.html
{% extends "base.html" %}

{% block title %}
Login
{% endblock %}

{% block content %}
<div class="content-wrap">
    <form action="{{ url_for('users.signup') }}{% if next %}?next={{ next }}{% endif %}" method="post" id="login-form">
        <h3>Registration form</h3>
        <div class="input-wrap">
            <label for="username">Username</label>
            <input type="text" name="username" id="username" placeholder="Enter your username" />
        </div>
        <div class="input-wrap">
            <label for="password">Password</label>
            <input type="password" name="password" id="password" placeholder="Enter your password" />
        </div>
        <div class="controls input-wrap">
            <button type="submit">Register</button>
        </div>
        <br />
        <br />
        <br />
        <div class="signup2">
            You have an account? <a href="{{ url_for('users.login') }}">Login</a>
        </div>
    </form>
</div>
{% endblock %}