app/privileges/__init__.py
# app/admin/__init__.py

from flask import Blueprint


def import_views():
    from . import views
    from app import models


privileges = Blueprint('privileges', __name__)
import_views()

app/privileges/views.py
# app/home/views.py

from flask import render_template, request, redirect, session
from app import main_nav, db
from . import privileges
from app.models import Privilege
from sqlalchemy import text
from flask_login import login_required, current_user


@privileges.route('/')
@login_required
def index():
    navs = main_nav('Privileges')
    q = request.args.get('q')
    if not q:
        privileges = Privilege.query.all()
    else:
        privileges = Privilege.query.filter(Privilege.name.like('%'+q+'%'))
    return render_template('privileges/index.html', privileges=privileges, navs=navs, title="Privileges")


@privileges.route('/manage', methods=['GET', 'POST'])
@privileges.route('/manage/<id>', methods=['GET', 'POST'])
@login_required
def manage(id=None):
    navs = main_nav('Privileges')
    if request.method == 'POST':
        data = request.form
        id = data['id']
        if id:
            m = Privilege.query.get(id)
            m.name = data['name']
        else:
            m = Privilege(name=data['name'])
            db.session.add(m)
        db.session.commit()
        return redirect("/privileges", code=302)
    else:
        privilege = None
        if id:
            privilege = Privilege.query.get(id)
        return render_template('privileges/manage.html', navs=navs, title="Privileges", privilege=privilege)


@privileges.route('/delete/<id>')
@login_required
def delete(id=None):
    m = Privilege.query.get(id)
    db.session.delete(m)
    db.session.commit()
    return redirect("/privileges", code=302)


@privileges.route('/deleteall')
@login_required
def deleteall():
    # Delete all here
    return redirect("/privileges", code=302)

app/templates/privileges/index.html
{% extends "base.html" %}

{% block title %}
Privileges
{% endblock %}

{% block breadcrumbs %}
<ul>
    <li><a href="/">Home</a></li>
    <li><span>Privileges</span></li>
</ul>
{% endblock %}

{% block content %}
<div class="content-wrap table-container">
    <h3>List of privileges</h3>
    <div class="tablebar">
        <div class="search">
            <form action="{{ url_for('privileges.index') }}">
                <input type="text" name="q" placeholder="Search privileges by name" /><button type="submit" class="search"><i
                        class="fa fa-search"></i></button>
            </form>
        </div>
        <div class="table-controls">
            <a href="{{ url_for('privileges.deleteall') }}" class="danger">Delete all</a>
            <a href="{{ url_for('privileges.manage') }}">Add</a>
        </div>
    </div>
    <div class="table-container">
        <table class="manage">
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Last update</th>
                <th>Manage</th>
            </tr>
            {% for m in privileges %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ m.name }}</td>
                <td>{{ m.last_update }}</td>
                <td>
                    <ul class="manage-btns">
                        <li class="delete"><a href="{{ url_for('privileges.delete', id=m.id) }}">Delete</a></li>
                        <li class="edit"><a href="{{ url_for('privileges.manage', id=m.id) }}">Edit</a></li>
                    </ul>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

app/templates/privileges/manage.html
{% extends "base.html" %}

{% block title %}
Privileges
{% endblock %}

{% block breadcrumbs %}
<ul>
    <li><a href="/">Home</a></li>
    <li><a href="{{ url_for('privileges.index') }}">Privileges</a></li>
    <li><span>Manage</span></li>
</ul>
{% endblock %}

{% block content %}
<div class="content-wrap">
    <h3>{% if privilege %}Edit {% else %}Add new {% endif %} privilege</h3>
    <form class="form" action="{{ url_for('privileges.manage') }}" method="post">
        <fieldset>
            <input type="hidden" name="id" {% if group %} value="{{ privilege.id }}" {% endif %} />
            <div>
                <div class="input-grp float-container">
                    <label for="name">Name:</label>
                    <input autocomplete="off" type="text" name="name" id="name" data-placeholder="Enter name" {% if
                        privilege %} value="{{ privilege.name }}" {% endif %} />
                </div>
                <div class="input-grp">
                    <button type="submit">Save</button>
                </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}