app/members/__init__.py
# app/admin/__init__.py

from flask import Blueprint


def import_views():
    from . import views
    from app import models


members = Blueprint('members', __name__)
import_views()

app/members/views.py
# app/home/views.py

from flask import render_template, request, redirect, session
from app import main_nav, db
from . import members
from app.models import Member, Payment, Contribution
from sqlalchemy import text
from flask_login import login_required


@members.route('/')
@login_required
def index():
    navs = main_nav('Members')
    q = request.args.get('q')
    if not q:
        members = Member.query.all()
    else:
        members = Member.query.filter(Member.name.like('%'+q+'%'))
    msg = session.get('msg')
    session['msg'] = None
    return render_template('members/index.html', members=members, navs=navs, title="Members", msg=msg)


def into_list(res):
    return [r for r in res]


def pending_list(id):
    sql = text(
        'select * from  vw_member_contributions where member_id = :member_id and (pending =1 or pending is null) order by last_update desc')
    return into_list(db.engine.execute(sql, {'member_id': id}))


def recent_list(id):
    sql = text(
        'select c.*, p.amount, p.record_date as pay_date from tbl_payment p left join tbl_contribution c on p.contribution_id = c.id where p.member_id = :member_id order by p.record_date desc limit 3')
    return into_list(db.engine.execute(sql, {'member_id': id}))


def eligible_roles():
    sql = text(
        'select r.* from tbl_role r')
    return into_list(db.engine.execute(sql, {}))


def eligible_groups():
    sql = text(
        'select g.* from tbl_group g order by g.name asc')
    return into_list(db.engine.execute(sql, {}))


@members.route('/payments/<id>', methods=['GET', 'POST'])
@login_required
def payments(id=None):
    navs = main_nav('Members')
    if request.method == 'POST':
        data = request.form
        m = Payment(member_id=data['member_id'],
                    contribution_id=data['contribution_id'], amount=data['amount'])
        db.session.add(m)
        db.session.commit()
        return redirect('/members/payments/{}'.format(id), code=302)
    else:
        member = Member.query.get(id)
        pending = pending_list(id)

        balance = 0
        for pc in pending:
            balance += pc.balance or pc.price
        recent = recent_list(id)
        print('Pending: ', pending)
        return render_template('members/payments.html', navs=navs, title="Members", member=member, pending=pending, recent=recent, balance=balance)


@members.route('/manage', methods=['GET', 'POST'])
@members.route('/manage/<id>', methods=['GET', 'POST'])
@login_required
def manage(id=None):
    navs = main_nav('Members')
    if request.method == 'POST':
        data = request.form
        id = data['id']
        if id:
            m = Member.query.get(id)
            m.name = data['name']
            m.group_id = data['group_id']
            # db.session.update(m)
        else:
            m = Member(name=data['name'])
            m.group_id = data['group_id']
            db.session.add(m)
        db.session.commit()
        return redirect("/members", code=302)
    else:
        groups = eligible_groups()
        member = None
        if id:
            member = Member.query.get(id)
        return render_template('members/manage.html', navs=navs, title="Members", member=member, groups=groups)


@members.route('/role/<id>', methods=['GET', 'POST'])
@login_required
def role(id=None):
    navs = main_nav('Members')
    if request.method == 'POST':
        data = request.form
        id = data['id']
        if id:
            m = Member.query.get(id)
            m.role_id = data['role_id']
            m.username = data['username']
        db.session.commit()
        return redirect("/members", code=302)
    else:
        roles = eligible_roles()
        member = None
        if id:
            member = Member.query.get(id)
        return render_template('members/role.html', navs=navs, title="Members", member=member, roles=roles)


@members.route('/delete/<id>')
@login_required
def delete(id=None):
    m = Member.query.get(id)
    db.session.delete(m)
    db.session.commit()
    session['msg'] = 'Successfully deleted a member'
    return redirect("/members", code=302)

app/roles/__init__.py
# app/admin/__init__.py

from flask import Blueprint


def import_views():
    from . import views
    from app import models


roles = Blueprint('roles', __name__)
import_views()

app/roles/views.py
# app/home/views.py

from flask import render_template, request, redirect, session, flash
from app import main_nav, db
from . import roles
from app.models import Role, RolePrivilege as RP, Privilege
from sqlalchemy import text
from flask_login import login_required, current_user


@roles.route('/')
@login_required
def index():
    navs = main_nav('Roles')
    q = request.args.get('q')
    if not q:
        roles = Role.query.all()
    else:
        roles = Role.query.filter(Role.name.like('%'+q+'%'))
    return render_template('roles/index.html', roles=roles, navs=navs)


@roles.route('/matrix', methods=['POST'])
@roles.route('/matrix/<id>', methods=['GET'])
@login_required
def matrix(id=None):
    navs = main_nav('Roles')
    if request.method == 'POST':
        data = request.form
        id = data['id']
        privileges = data['privileges']
        print(privileges)
        RP.query.filter(RP.role_id == id).delete()
        db.session.commit()
        for p in privileges:
            new_rp = RP(role_id=id, privilege_id=p)
            db.session.add(new_rp)
        db.session.commit()
        flash('Role matrix updated successfully')
        return redirect("/roles", code=302)
    else:
        role = None
        if id:
            role = Role.query.get(id)
        privileges = Privilege.query.all()
        return render_template('roles/matrix.html', navs=navs, role=role, privileges=privileges)


@roles.route('/manage', methods=['GET', 'POST'])
@roles.route('/manage/<id>', methods=['GET', 'POST'])
@login_required
def manage(id=None):
    navs = main_nav('Roles')
    if request.method == 'POST':
        data = request.form
        id = data['id']
        if id:
            m = Role.query.get(id)
            m.name = data['name']
        else:
            m = Role(name=data['name'])
            db.session.add(m)
        db.session.commit()
        return redirect("/roles", code=302)
    else:
        role = None
        if id:
            role = Role.query.get(id)
        return render_template('roles/manage.html', navs=navs, role=role)


@roles.route('/delete/<id>')
@login_required
def delete(id=None):
    m = Role.query.get(id)
    db.session.delete(m)
    db.session.commit()
    return redirect("/roles", code=302)


@roles.route('/deleteall')
@login_required
def deleteall():
    # Delete all here
    return redirect("/roles", code=302)

app/templates/members/index.html
{% extends "base.html" %}

{% block title %}
Members
{% endblock %}

{% block breadcrumbs %}
<ul>
    <li><a href="/">Home</a></li>
    <li><span>Members</span></li>
</ul>
{% endblock %}

{% block content %}
<div class="content-wrap table-container">
    <h3>List of members</h3>
    {% if msg %}
    <p class="flash">
        {{msg}} <span><a href="/members">X</a></span>
    </p>
    {% endif %}
    <div class="tablebar">
        <div class="search">
            <form action="/members">
                <input type="text" name="q" placeholder="Search members by name" /><button type="submit" class="search"><i
                        class="fa fa-search"></i></button>
            </form>
        </div>
        <div class="table-controls">
            <a href="/members/deleteall" class="danger">Delete all</a>
            <a href="/members/manage">Add</a>
        </div>
    </div>
    <div class="table-container">
        <table class="manage">
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Group</th>
                <th>Member role</th>
                <th>Manage</th>
            </tr>
            {% for m in members%}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ m.name }}</td>
                <td>{{ m.group.name }}</td>
                <td>{{ m.role.name or 'Not set'}} <a href="/members/role/{{ m.id }}"><i class="far fa-edit"></i></a></td>
                <td>
                    <ul class="manage-btns">
                        <li class="delete"><a href="/members/delete/{{ m.id }}">Delete</a></li>
                        <li class="edit"><a href="/members/manage/{{ m.id }}">Edit</a></li>
                        <li class="edit"><a href="/members/payments/{{ m.id }}">Contributions</a></li>
                    </ul>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

app/templates/members/manage.html
{% extends "base.html" %}

{% block title %}
Members
{% endblock %}

{% block breadcrumbs %}
<ul>
    <li><a href="/">Home</a></li>
    <li><a href="/members">Members</a></li>
    <li><span>Manage</span></li>
</ul>
{% endblock %}

{% block content %}
<div class="content-wrap">
    <h3>{% if member %}Edit {% else %}Add new {% endif %} member</h3>
    <form class="form" action="/members/manage" method="post">
        <fieldset>
            <!--legend>Manage a member</legend-->
            <input type="hidden" name="id" {% if member %} value="{{ member.id }}" {% endif %} />
            <div>
                <div class="input-grp float-container">
                    <label for="name">Name:</label>
                    <input autocomplete="off" type="text" name="name" id="name" data-placeholder="Enter name" {% if
                        member %} value="{{ member.name }}" {% endif %} />
                </div>
                <div class="input-grp select">
                    <label for="name">Group:</label>
                    <select name="group_id" id="group_id">
                        {% for g in groups %}
                        <option {% if member.group %} selected="selected" {% endif %} value="{{ g.id }}">{{ g.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="input-grp">
                    <button type="submit">Save</button>
                </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

app/templates/members/payments.html
{% extends "base.html" %}

{% block title %}
Payments
{% endblock %}

{% block breadcrumbs %}
<ul>
    <li><a href="/">Home</a></li>
    <li><a href="/members">Members</a></li>
    <li><span>Payments</span></li>
</ul>
{% endblock %}

{% block content %}
<div id="member-contributions" class="content-wrap table-container">
    <div class="profile">
        <div class="row">
            <div class="label">Member name: </div>
            <div class="name">{{ member.name }}</div>
        </div>
        <div class="row">
            <div class="label">Total balance(TZS): </div>
            <div class="name">{{ balance }}</div>
        </div>
    </div>
    <div class="payments">
        <div class="pending table-container">
            <h3>List of pending contributions</h3>
            <table>
                <tr>
                    <th>#</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Balance</th>
                </tr>
                {% for c in pending %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td>{{ c.name }}</td>
                    <td>{{ c.price }}</td>
                    <td>
                        <div class="pay">
                            <form action="/members/payments/{{ member.id }}" method="post">
                                <input type="hidden" name="member_id" value="{{ member.id }}" />
                                <input type="hidden" name="contribution_id" value="{{ c.contribution_id }}" />
                                <input type="number" name="amount" placeholder="Enter amount" {% if c.balance is not
                                    none %} value="{{ c.balance }}" {% else %} value="{{ c.price }}" {% endif %} min="500"
                                    max="100000" step="500" />
                                <button type="submit" {% if not c.pending and c.pending is not none %} disabled="disabled"
                                    {% endif %}>Pay</button>
                            </form>

                        </div>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="recent">
            <h3>List of recent contributions</h3>
            {% for p in recent %}
            <div class="row">
                <i class="fas fa-angle-right"></i>
                <ul class="main">
                    <li>{{ p.pay_date }}
                        <ul class="details">
                            <li>{{ p.name }}</li>
                            <li><span class="amount">TZS: {{ p.amount }}</span></li>
                        </ul>
                    </li>

                </ul>
            </div>
            {% else %}
            <i class="norecords">No reconds found</i>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/members/role.html
{% extends "base.html" %}

{% block title %}
Members
{% endblock %}

{% block breadcrumbs %}
<ul>
    <li><a href="/">Home</a></li>
    <li><a href="/members">Members</a></li>
    <li><span>Role</span></li>
</ul>
{% endblock %}

{% block content %}
<div class="content-wrap">
    <h3>Edit member role</h3>
    <form class="form" action="{{ url_for('members.role', id=member.id) }}" method="post">
        <fieldset>
            <input type="hidden" name="id" {% if member %} value="{{ member.id }}" {% endif %} />
            <div>
                <div class="input-grp float-container">
                    <label for="username">Member login:</label>
                    <input autocomplete="off" type="text" name="username" id="username" data-placeholder="Enter your username"
                        value="{{ member.username or '' }}" />
                </div>
                <div class="input-grp select">
                    <label for="role_id">Member role:</label>
                    <select name="role_id" id="role_id">
                        {% for r in roles %}
                        <option {% if member.role_id %} selected="selected" {% endif %} value="{{ r.id }}">{{ r.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="input-grp">
                    <button type="submit">Save</button>
                </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}