app/roles/__init__.py
# app/admin/__init__.py

from flask import Blueprint


def import_views():
    from . import views
    from app import models


roles = Blueprint('roles', __name__)
import_views()

app/roles/views.py
# app/home/views.py

from flask import render_template, request, redirect, session, flash
from app import main_nav, db
from . import roles
from app.models import Role, RolePrivilege as RP, Privilege
from sqlalchemy import text
from flask_login import login_required, current_user


@roles.route('/')
@login_required
def index():
    navs = main_nav('Roles')
    q = request.args.get('q')
    if not q:
        roles = Role.query.all()
    else:
        roles = Role.query.filter(Role.name.like('%'+q+'%'))
    return render_template('roles/index.html', roles=roles, navs=navs)


@roles.route('/matrix', methods=['POST'])
@roles.route('/matrix/<id>', methods=['GET'])
@login_required
def matrix(id=None):
    navs = main_nav('Roles')
    if request.method == 'POST':
        data = request.form
        id = data['id']
        privileges = data['privileges']
        print(privileges)
        RP.query.filter(RP.role_id == id).delete()
        db.session.commit()
        for p in privileges:
            new_rp = RP(role_id=id, privilege_id=p)
            db.session.add(new_rp)
        db.session.commit()
        flash('Role matrix updated successfully')
        return redirect("/roles", code=302)
    else:
        role = None
        if id:
            role = Role.query.get(id)
        privileges = Privilege.query.all()
        return render_template('roles/matrix.html', navs=navs, role=role, privileges=privileges)


@roles.route('/manage', methods=['GET', 'POST'])
@roles.route('/manage/<id>', methods=['GET', 'POST'])
@login_required
def manage(id=None):
    navs = main_nav('Roles')
    if request.method == 'POST':
        data = request.form
        id = data['id']
        if id:
            m = Role.query.get(id)
            m.name = data['name']
        else:
            m = Role(name=data['name'])
            db.session.add(m)
        db.session.commit()
        return redirect("/roles", code=302)
    else:
        role = None
        if id:
            role = Role.query.get(id)
        return render_template('roles/manage.html', navs=navs, role=role)


@roles.route('/delete/<id>')
@login_required
def delete(id=None):
    m = Role.query.get(id)
    db.session.delete(m)
    db.session.commit()
    return redirect("/roles", code=302)


@roles.route('/deleteall')
@login_required
def deleteall():
    # Delete all here
    return redirect("/roles", code=302)

app/templates/roles/index.html
{% extends "base.html" %}

{% block title %}
Roles
{% endblock %}

{% block breadcrumbs %}
<ul>
    <li><a href="/">Home</a></li>
    <li><span>Roles</span></li>
</ul>
{% endblock %}

{% block content %}
<div class="content-wrap table-container">
    <h3>List of roles</h3>
    <div class="tablebar">
        <div class="search">
            <form action="{{ url_for('roles.index') }}">
                <input type="text" name="q" placeholder="Search roles by name" /><button type="submit" class="search"><i
                        class="fa fa-search"></i></button>
            </form>
        </div>
        <div class="table-controls">
            <a href="{{ url_for('roles.deleteall') }}" class="danger">Delete all</a>
            <a href="{{ url_for('roles.manage') }}">Add</a>
        </div>
    </div>
    <div class="table-container">
        <table class="manage">
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Last update</th>
                <th>Manage</th>
            </tr>
            {% for m in roles %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ m.name }}</td>
                <td>{{ m.last_update }}</td>
                <td>
                    <ul class="manage-btns">
                        <li class="delete"><a href="{{ url_for('roles.delete', id=m.id) }}">Delete</a></li>
                        <li class="edit"><a href="{{ url_for('roles.manage', id=m.id) }}">Edit</a></li>
                        <li class="edit"><a href="{{ url_for('roles.matrix', id=m.id) }}">Matrix</a></li>
                    </ul>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

app/templates/roles/manage.html
{% extends "base.html" %}

{% block title %}
Roles
{% endblock %}

{% block breadcrumbs %}
<ul>
    <li><a href="/">Home</a></li>
    <li><a href="{{ url_for('roles.index') }}">Roles</a></li>
    <li><span>Manage</span></li>
</ul>
{% endblock %}

{% block content %}
<div class="content-wrap">
    <h3>{% if role %}Edit {% else %}Add new {% endif %} role</h3>
    <form class="form" action="{{ url_for('roles.manage') }}" method="post">
        <fieldset>
            <input type="hidden" name="id" {% if group %} value="{{ role.id }}" {% endif %} />
            <div>
                <div class="input-grp float-container">
                    <label for="name">Name:</label>
                    <input autocomplete="off" type="text" name="name" id="name" data-placeholder="Enter name" {% if
                        role %} value="{{ role.name }}" {% endif %} />
                </div>
                <div class="input-grp">
                    <button type="submit">Save</button>
                </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

app/templates/roles/matrix.html
{% extends "base.html" %}

{% block title %}
Roles
{% endblock %}

{% block breadcrumbs %}
<ul>
    <li><a href="/">Home</a></li>
    <li><a href="{{ url_for('roles.index') }}">Roles</a></li>
    <li><span>Matrix</span></li>
</ul>
{% endblock %}

{% block content %}
<div class="content-wrap table-container">
    <h3>Role matrix for: <u>{{ role.name }}</u></h3>
    <div class="matrix">
        <form action="{{ url_for('roles.matrix') }}" method="post">
            <input type="hidden" name="id" value="{{ role.id }}" />
            <ul>
                <li>
                    <div class="input-grp">
                        <button type="submit">Save</button>
                    </div>
                </li>
                <li><b>Privileges:</b>
                    <ul>
                        {% for p in privileges %}
                        <li>
                            <div class="input-grp checkbox">
                                <input type="checkbox" name="privileges" value="{{ p.id }}" /><label>{{ p.name }}</label>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
        </form>
    </div>
</div>
{% endblock %}